name: Check Code and Build

on:
  push:
    branches:
      - "main"

env:
  VERSION: ${{github.ref_name}}

jobs:
  check_codebase:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:

    - uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Requirements
      run: |
        pip install -r requirements.txt
        pip install bandit

    - name: Check Security
      run: |
        make securityCheck


  build:
    runs-on: ubuntu-latest
    needs: check_codebase
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:

    - uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build Image
      run: |
        make dockerBuild